services:
  db:
    image: postgres:17-alpine
    container_name: db-dev
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: backend-dev
    build:
      context: "../../backend"
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    env_file:
      - ./.env.dev
    ports:
      - 3456:3456
    volumes:
      - "../../backend:/app/backend"
      - /app/backend/node_modules
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: "../../frontend"
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    env_file:
      - "../../frontend/.env.local"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - "../../frontend:/app/frontend"
      - /app/frontend/node_modules
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_db: {}
