services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ../../nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: "../../backend"
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    ports:
      - 3456:3456
    volumes:
      - "../../backend:/app/backend"
      - /app/backend/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: "../../frontend"
      dockerfile: Dockerfile.dev
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    env_file:
      - ../../frontend/.env.local
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - "../../frontend:/app/frontend"
      - /app/frontend/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
