services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ../../nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: "../../backend"
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    env_file:
      - ./.env.dev
    ports:
      - 3456:3456
    volumes:
      - "../../backend:/app/backend"
      - /app/backend/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: "../../frontend"
      dockerfile: Dockerfile.dev
    container_name: frontend
    env_file:
      - ./.env.dev
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - "../../frontend:/app/frontend"
      - /app/frontend/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_db: {}
