services:
  db:
    image: postgres:17-alpine
    container_name: db-prod
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: backend-prod
    image: backend-prod:latest
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - ./.env.prod
    ports:
      - "3456:3456"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    container_name: frontend-prod
    image: frontend-prod:latest
    restart: always
    env_file:
      - ./.env.prod
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_db: {}
