version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: db-prod
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: "../../backend"
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    env_file:
      - ./.env.prod
    ports:
      - "3456:3456"
    environment:
      FRONTEND_URL: http://frontend:3000 # Frontend URL for CORS
    networks:
      - app-network

  frontend:
    build:
      context: "../../frontend"
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    env_file:
      - ../../frontend/.env.local
    ports:
      - "3000:3000" # Expose frontend on port 3000
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3456/api # Point to the backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_db: {}
