services:
  db:
    image: postgres:17-alpine
    container_name: db-prod
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    # build:
    #   context: "../../backend"
    #   dockerfile: Dockerfile.prod
    image: backend-prod:latest
    container_name: backend-prod
    ports:
      - 127.0.0.1:3456:3456
    env_file:
      - ./.env.prod
    networks:
      - app-network

  frontend:
    # build:
    #   context: "../../frontend"
    #   dockerfile: Dockerfile.prod
    image: frontend-prod:latest
    container_name: frontend-prod
    env_file:
      - ../../frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres_db: {}
